# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8004d3fdaefa774c0c596847171b8b71c8892de3a09d690fdce168de9f0844b1ab8d7adae886d60f5de69f7b6899445c74a73f081d01abef41bfe49f7b965f57

test:
  secret_key_base: b7058bb53eab749729c3c2b92560ae762e58467d40b572fefa55a5fee6c35e81c1ee000a0f2e4743fc7515f2eca137b216c0ddd01aeada6031f10c2b94e38295

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
